[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'Iniciando build Netlify...'" # Removido o comando npm complexo
  
  [build.environment]
    NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild" # Usa o bundler mais moderno e confiável

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 
