[build]
  # Configuração de Build
  functions = "netlify/functions"
  publish = "." # Onde o index.html está

[[headers]]
  for = "/*"
  [headers.values]
    # Mantemos o CORS para garantir que o navegador não bloqueie
    Access-Control-Allow-Origin = "*" 
